<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pluto">

  <xacro:property name="base_width" value="0.508"/>
  <xacro:property name="base_length" value="0.508"/>
  <xacro:property name="base_height" value="0.508"/>
  <xacro:property name="wheel_radius" value="0.1016"/>
  <xacro:property name="base_wheel_gap" value="0.0125"/>
  <xacro:property name="wheel_separation" value="0.5205"/>
  <xacro:property name="wheel_joint_offset" value="0.02"/>
  <xacro:property name="caster_wheel_radius" value="0.0125"/>
  
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
    </inertial>
  </xacro:macro>
  
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
    </inertial>
  </xacro:macro>
  
  <link name="base_footprint">
    <xacro:box_inertia m="1" w="0.001" h="0.001" d="0.001"/>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>
  
  <link name="base_link">
    <xacro:box_inertia m="1" w="${base_length}" h="${base_width}" d="${base_height}"/>
    <visual>
      <origin xyz="-0.015 -0.00275 0" rpy="0 0 0" />
      <geometry>
        <!--box size="${base_length} ${base_width} ${base_height}" /-->
        <mesh filename="package://pluto/models/Chassis.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.015 -0.00275 0" rpy="0 0 0" />
      <geometry>
        <!--box size="${base_length} ${base_width} ${base_height}"/-->
        <mesh filename="package://pluto/models/Chassis.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
 
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>
  
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://pluto/models/Wheel.dae" scale="1 1 1"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>        	
          <mesh filename="package://pluto/models/Wheel.dae" scale="1 1 1"/>
          <!--cylinder radius="${wheel_radius}" length="0.0508"/-->
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="10" r="${wheel_radius}" h="0.0508"/>
    </link>
 
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="-0.0725 ${((base_width/4) - base_wheel_gap)*reflect} ${((wheel_radius/4) + 0.007)}" rpy="0 0 0" />
    </joint>
  </xacro:macro>
 
  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>
  
  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}"/>
    </inertial>
  </xacro:macro>
 
   <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="5" r="${caster_wheel_radius}"/>
  </link>
 
  <joint name="caster_wheel_joint" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.085 0 0.004" rpy="0 0 0"/>
  </joint>
  
  <link name="torso">
    <xacro:box_inertia m="2" w="0.254" h="0.4572" d="0.1778"/>
    <visual>
      <origin xyz="0 0 0.32" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Torso.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.32" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Torso.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="torso_joint" type="revolute">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="torso" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  
  <link name="head">
    <xacro:box_inertia m="1" w="0.1778" h="0.1778" d="0.1778"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Head.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Head.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="head_joint" type="revolute">
    <origin xyz="0.01 0 0.47" rpy="0 0 0" />
    <axis xyz="0 0 1" rpy="0 0 0" />
    <parent link="torso"/>
    <child link="head" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  
  <xacro:macro name="shoulder" params="prefix reflect flip">
    <link name="${prefix}_shoulder">
      <visual>
        <origin xyz="0 0 0" rpy="${flip} 0 0"/>
        <geometry>
          <mesh filename="package://pluto/models/Shoulder.dae" scale="1 1 1"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${flip} 0 0"/>
        <geometry>        	
          <mesh filename="package://pluto/models/Shoulder.dae" scale="1 1 1"/>
        </geometry>
        <surface>
         <friction>
          <ode>
            <mu>0.01</mu>
            <mu2>0.01</mu2>
          </ode>
         </friction>
        </surface>
      </collision>
      <xacro:cylinder_inertia m="3" r="0.0381" h="0.0889"/>
    </link>
 
    <joint name="${prefix}_shoulder_joint" type="revolute">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="torso"/>
      <child link="${prefix}_shoulder"/>
      <origin xyz="0 ${(0.055 * reflect)} 0.372" rpy="0 0 0" />
      <limit effort="30.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
    </joint>
  </xacro:macro>
 
  <xacro:shoulder prefix="left" reflect="1" flip= "${(pi)}"/>
  <xacro:shoulder prefix="right" reflect="-1" flip= "0"/>
  
  <xacro:macro name="upper_arm_bottom" params="prefix reflect flip">
   <link name="${prefix}_upper_arm_bottom">
     <visual>
       <origin xyz="0 0 0" rpy="0 0 ${flip}"/>
       <geometry>
         <mesh filename="package://pluto/models/UpperArmBottom.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/UpperArmBottom.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>0.01</mu>
            <mu2>0.01</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.5" r="0.03175" h="0.254"/>
   </link>
 
   <joint name="${prefix}_upper_arm_bottom_joint" type="revolute">
     <axis xyz="1 0 0" rpy="0 0 0" />
     <parent link="${prefix}_shoulder"/>
     <child link="${prefix}_upper_arm_bottom"/>
     <origin xyz="0 ${(0.0225 * reflect)} 0" rpy="0 0 0" />
     <limit effort="30.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:upper_arm_bottom prefix="left" reflect="1" flip= "${(pi)}"/>
  <xacro:upper_arm_bottom prefix="right" reflect="-1" flip= "0"/>
  
  <xacro:macro name="upper_arm_top" params="prefix reflect flip">
   <link name="${prefix}_upper_arm_top">
     <visual>
       <origin xyz="0 0 0" rpy="0 0 ${flip}"/>
       <geometry>
         <mesh filename="package://pluto/models/UpperArmTop.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/UpperArmTop.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>0.01</mu>
            <mu2>0.01</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="4" r="0.03175" h="0.254"/>
   </link>
 
   <joint name="${prefix}_upper_arm_top_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_upper_arm_bottom"/>
     <child link="${prefix}_upper_arm_top"/>
     <origin xyz="0 0 -0.03125" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:upper_arm_top prefix="left" reflect="1" flip= "${(pi)}"/>
  <xacro:upper_arm_top prefix="right" reflect="-1" flip= "0"/>

  <xacro:macro name="forearm_bottom" params="prefix reflect flip">
   <link name="${prefix}_forearm_bottom">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/ForearmBottom.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/ForearmBottom.dae" scale="1 1 1"/>
       </geometry>
       <!--surface>
         <friction>
          <ode>
            <mu>1000.0</mu>
            <mu2>1000.0</mu2>
          </ode>
         </friction>
       </surface-->
     </collision>
     <xacro:cylinder_inertia m="0.5" r="0.03175" h="0.1016"/>
   </link>
 
   <joint name="${prefix}_forearm_bottom_joint" type="revolute">
     <axis xyz="0 1 0" rpy="0 0 0" />
     <parent link="${prefix}_upper_arm_top"/>
     <child link="${prefix}_forearm_bottom"/>
     <origin xyz="0 ${(0 * reflect)} -0.07625" rpy="0 ${pi/2} 0" />
     <limit effort="10.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
     <dyanamics damping="10.0" friction="10.0" />
   </joint>
  </xacro:macro>
 
  <xacro:forearm_bottom prefix="left" reflect="1" flip= "${(pi)}"/>
  <xacro:forearm_bottom prefix="right" reflect="-1" flip= "0"/>

  <xacro:macro name="forearm_top" params="prefix reflect flip">
   <link name="${prefix}_forearm_top">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/ForearmTop.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/ForearmTop.dae" scale="1 1 1"/>
       </geometry>
       <!--surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface-->
     </collision>
     <xacro:cylinder_inertia m="0.4" r="0.03175" h="0.1016"/>
   </link>
 
   <joint name="${prefix}_forearm_top_joint" type="revolute">
     <axis xyz="1 0 0" rpy="0 0 0" />
     <parent link="${prefix}_forearm_bottom"/>
     <child link="${prefix}_forearm_top"/>
     <origin xyz="0.029 ${(0 * reflect)} 0" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:forearm_top prefix="left" reflect="1" flip= "${(pi)}"/>
  <xacro:forearm_top prefix="right" reflect="-1" flip= "0"/>
  
  <link name="right_palm">
    <xacro:box_inertia m="0.3" w="0.127" h="0.127" d="0.0254"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/RightPalm.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/RightPalm.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="right_palm_joint" type="revolute">
    <origin xyz="0.06525 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" rpy="0 0 0" />
    <parent link="right_forearm_top"/>
    <child link="right_palm" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  
  <link name="left_palm">
    <xacro:box_inertia m="0.3" w="0.127" h="0.127" d="0.0254"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/LeftPalm.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/LeftPalm.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="left_palm_joint" type="revolute">
    <origin xyz="0.06525 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" rpy="0 0 0" />
    <parent link="left_forearm_top"/>
    <child link="left_palm" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  
  <link name="right_palm_surface">
    <xacro:box_inertia m="0.02" w="0.127" h="0.127" d="0.0254"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/RightPalmSurface.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/RightPalmSurface.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="right_palm_surface_joint" type="fixed">
    <origin xyz="0.004 0.00275 0" rpy="0 0 0" />
    <parent link="right_palm"/>
    <child link="right_palm_surface" />
  </joint>
  
  <link name="left_palm_surface">
    <xacro:box_inertia m="0.02" w="0.127" h="0.127" d="0.0254"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/LeftPalmSurface.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/LeftPalmSurface.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="left_palm_surface_joint" type="fixed">
    <origin xyz="0.004 -0.00275 0" rpy="0 0 0" />
    <parent link="left_palm"/>
    <child link="left_palm_surface" />
  </joint>
  
  <xacro:macro name="index_bottom" params="prefix reflect flip offset">
   <link name="${prefix}_index_bottom">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/IndexBottom.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/IndexBottom.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_index_bottom_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_palm"/>
     <child link="${prefix}_index_bottom"/>
     <origin xyz="0.0395 ${(0.0025 * reflect)} ${(offset + 0.0132)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
     <dyanamics damping="10.0" friction="10.0" />
   </joint>
  </xacro:macro>
 
  <xacro:index_bottom prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:index_bottom prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <xacro:macro name="middle_bottom" params="prefix reflect flip offset">
   <link name="${prefix}_middle_bottom">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/MiddleBottom.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/MiddleBottom.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_middle_bottom_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_palm"/>
     <child link="${prefix}_middle_bottom"/>
     <origin xyz="0.0395 ${(0.00325 * reflect)} ${(offset + 0.00425)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:middle_bottom prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:middle_bottom prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <xacro:macro name="ring_bottom" params="prefix reflect flip offset">
   <link name="${prefix}_ring_bottom">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/RingBottom.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/RingBottom.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_ring_bottom_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_palm"/>
     <child link="${prefix}_ring_bottom"/>
     <origin xyz="0.0395 ${(0.00325 * reflect)} ${(offset - 0.00425)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:ring_bottom prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:ring_bottom prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <xacro:macro name="pinky_bottom" params="prefix reflect flip offset">
   <link name="${prefix}_pinky_bottom">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/PinkyBottom.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/PinkyBottom.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_pinky_bottom_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_palm"/>
     <child link="${prefix}_pinky_bottom"/>
     <origin xyz="0.0395 ${(0.00325 * reflect)} ${(offset - 0.0125)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:pinky_bottom prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:pinky_bottom prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <xacro:macro name="index_top" params="prefix reflect flip offset">
   <link name="${prefix}_index_top">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/IndexTop.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/IndexTop.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_index_top_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_index_bottom"/>
     <child link="${prefix}_index_top"/>
     <origin xyz="0.019 ${(0.001 * reflect)} ${(offset)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:index_top prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:index_top prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <xacro:macro name="middle_top" params="prefix reflect flip offset">
   <link name="${prefix}_middle_top">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/MiddleTop.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/MiddleTop.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_middle_top_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_middle_bottom"/>
     <child link="${prefix}_middle_top"/>
     <origin xyz="0.0205 ${(0 * reflect)} ${(offset - 0.0002)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:middle_top prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:middle_top prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <xacro:macro name="ring_top" params="prefix reflect flip offset">
   <link name="${prefix}_ring_top">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/RingTop.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/RingTop.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_ring_top_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_ring_bottom"/>
     <child link="${prefix}_ring_top"/>
     <origin xyz="0.019 ${(-0.0005 * reflect)} ${(offset + 0.0002)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:ring_top prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:ring_top prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <xacro:macro name="pinky_top" params="prefix reflect flip offset">
   <link name="${prefix}_pinky_top">
     <visual>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>
         <mesh filename="package://pluto/models/PinkyTop.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${flip} 0 0"/>
       <geometry>        	
         <mesh filename="package://pluto/models/PinkyTop.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_pinky_top_joint" type="revolute">
     <axis xyz="0 0 1" rpy="0 0 0" />
     <parent link="${prefix}_pinky_bottom"/>
     <child link="${prefix}_pinky_top"/>
     <origin xyz="0.0145 ${(-0.00025 * reflect)} ${(offset + 0.0002)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:pinky_top prefix="left" reflect="1" flip= "${(pi)}" offset= "0"/>
  <xacro:pinky_top prefix="right" reflect="-1" flip= "0" offset= "0"/>
  
  <link name="right_thumb_piece">
    <xacro:box_inertia m="0.1" w="0.0508" h="0.0508" d="0.0254"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/RightThumbPiece.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/RightThumbPiece.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="right_thumb_piece_joint" type="revolute">
    <origin xyz="0.0135 -0.002 0.0125" rpy="0 0 0" />
    <axis xyz="1 0 0" rpy="0 0 0" />
    <parent link="right_palm"/>
    <child link="right_thumb_piece" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  
  <link name="left_thumb_piece">
    <xacro:box_inertia m="0.1" w="0.0508" h="0.0508" d="0.0254"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/LeftThumbPiece.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/LeftThumbPiece.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="left_thumb_piece_joint" type="revolute">
    <origin xyz="0.014 0.002 0.0125" rpy="0 0 0" />
    <axis xyz="1 0 0" rpy="0 0 0" />
    <parent link="left_palm"/>
    <child link="left_thumb_piece" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  
  <xacro:macro name="thumb_bottom" params="prefix reflect flip offset">
   <link name="${prefix}_thumb_bottom">
     <visual>
       <origin xyz="0 0 0" rpy="${(-pi/10 * reflect)} 0 ${(-pi/6 * reflect)}"/>
       <geometry>
         <mesh filename="package://pluto/models/ThumbBottom.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${(-pi/10 * reflect)} 0 ${(-pi/6 * reflect)}"/>
       <geometry>        	
         <mesh filename="package://pluto/models/ThumbBottom.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_thumb_bottom_joint" type="revolute">
     <axis xyz="0 1 0" rpy="0 0 ${(-pi/6 * reflect)}" />
     <parent link="${prefix}_thumb_piece"/>
     <child link="${prefix}_thumb_bottom"/>
     <origin xyz="0.0035 ${(0.00025 * reflect)} ${(offset + 0.011)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:thumb_bottom prefix="left" reflect="1" flip= "${-2*pi/10}" offset= "0"/>
  <xacro:thumb_bottom prefix="right" reflect="-1" flip= "0" offset="0"/>
  
  <xacro:macro name="thumb_top" params="prefix reflect flip offset">
   <link name="${prefix}_thumb_top">
     <visual>
       <origin xyz="0 0 0" rpy="${(-pi/10 * reflect)} 0 ${(-pi/6 * reflect)}"/>
       <geometry>
         <mesh filename="package://pluto/models/ThumbTop.dae" scale="1 1 1"/>
       </geometry>
     </visual>
     <collision>
       <origin xyz="0 0 0" rpy="${(-pi/10 * reflect)} 0 ${(-pi/6 * reflect)}"/>
       <geometry>        	
         <mesh filename="package://pluto/models/ThumbTop.dae" scale="1 1 1"/>
       </geometry>
       <surface>
         <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
         </friction>
       </surface>
     </collision>
     <xacro:cylinder_inertia m="0.02" r="0.00635" h="0.0508"/>
   </link>
 
   <joint name="${prefix}_thumb_top_joint" type="revolute">
     <axis xyz="0 1 0" rpy="0 0 ${(-pi/6 * reflect)}" />
     <parent link="${prefix}_thumb_bottom"/>
     <child link="${prefix}_thumb_top"/>
     <origin xyz="0.0125 ${(-0.0075 * reflect)} ${(offset + 0)}" rpy="0 0 0" />
     <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
   </joint>
  </xacro:macro>
 
  <xacro:thumb_top prefix="left" reflect="1" flip= "${-2*pi/10}" offset= "0"/>
  <xacro:thumb_top prefix="right" reflect="-1" flip= "0" offset="0"/>
  
  <!--link name="sensor_laser">
    <visual>
      <geometry>
        <box size="0.02  0.02  0.02"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.02  0.02  0.02"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.2" w="0.02" h="0.02" d="0.02"/>
  </link>
 
  <joint name="sensor_laser_joint" type="fixed">
    <origin xyz="0.01 0 0.525" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="sensor_laser" />
  </joint-->
  
  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>

  <joint name="imu_joint" type="fixed">
    <axis xyz="1 0 0"/> <!-- 0 1 0 -->
    <origin xyz="0 0 0.25"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>
  
  <xacro:include filename="$(find pluto)/urdf/pluto_plugins.xacro"/>
</robot>
