<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pluto">

  <xacro:property name="base_width" value="0.508"/>
  <xacro:property name="base_length" value="0.508"/>
  <xacro:property name="base_height" value="0.508"/>
  <xacro:property name="wheel_radius" value="0.1016"/>
  <xacro:property name="base_wheel_gap" value="0.0125"/>
  <xacro:property name="wheel_separation" value="0.5205"/>
  <xacro:property name="wheel_joint_offset" value="0.02"/>
  <xacro:property name="caster_wheel_radius" value="0.0125"/>
  
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12.0 * (d*d + h*h)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (w*w + h*h)}" iyz="0.0" izz="${m / 12.0 * (w*w + d*d)}"/>
    </inertial>
  </xacro:macro>
  
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}"/> 
    </inertial>
  </xacro:macro>
  
  <!--link name="base_footprint">
    <xacro:box_inertia m="10" w="0.001" h="0.001" d="0.001"/>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link -->
  
  <link name="base_link">
    <xacro:box_inertia m="10" w="${base_length}" h="${base_width}" d="${base_height}"/>
    <visual>
      <origin xyz="-0.015 -0.00275 0" rpy="0 0 0" />
      <geometry>
        <!--box size="${base_length} ${base_width} ${base_height}" /-->
        <mesh filename="package://pluto/models/Chassis.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.015 -0.00275 0" rpy="0 0 0" />
      <geometry>
        <!--box size="${base_length} ${base_width} ${base_height}"/-->
        <mesh filename="package://pluto/models/Chassis.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
 
  <!--joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint-->
  
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://pluto/models/Wheel.dae" scale="1 1 1"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>        	
          <mesh filename="package://pluto/models/Wheel.dae" scale="1 1 1"/>
          <!--cylinder radius="${wheel_radius}" length="0.0508"/-->
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="0.0508"/>
    </link>
 
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="-0.0725 ${((base_width/4) - base_wheel_gap)*reflect} ${((wheel_radius/4) + 0.007)}" rpy="0 0 0" />
    </joint>
  </xacro:macro>
 
  <xacro:wheel prefix="left" reflect="1"/>
  <xacro:wheel prefix="right" reflect="-1"/>
  
  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${2.0*m*(r*r)/5.0}" ixy="0.0" ixz="0.0" iyy="${2.0*m*(r*r)/5.0}" iyz="0.0" izz="${2.0*m*(r*r)/5.0}"/>
    </inertial>
  </xacro:macro>
 
   <link name="caster_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="1" r="${caster_wheel_radius}"/>
  </link>
 
  <joint name="caster_wheel_joint" type="continuous">
    <axis xyz="0 1 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.085 0 0.004" rpy="0 0 0"/>
  </joint>
  
  <link name="torso">
    <xacro:box_inertia m="2" w="0.254" h="0.4572" d="0.1778"/>
    <visual>
      <origin xyz="0 0 0.32" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Torso.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.32" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Torso.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="torso_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="torso" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  
  <link name="head">
    <xacro:box_inertia m="1" w="0.1778" h="0.1778" d="0.1778"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Head.dae" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://pluto/models/Head.dae" scale="1 1 1"/>
      </geometry>
    </collision>
  </link>
  
  <joint name="head_joint" type="revolute">
    <origin xyz="0.01 0 0.47" rpy="0 0 0" />
    <axis xyz="0 0 1" rpy="0 0 0" />
    <parent link="torso"/>
    <child link="head" />
    <limit effort="1.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="1.0"/>
  </joint>
  <link name="sensor_laser">
    <visual>
      <geometry>
        <box size="0.02  0.02  0.02"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.02  0.02  0.02"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.2" w="0.02" h="0.02" d="0.02"/>
  </link>
 
  <joint name="sensor_laser_joint" type="fixed">
    <origin xyz="0.01 0 0.525" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="sensor_laser" />
  </joint>
  
  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size=".001 .001 .001"/>
      </geometry>
    </collision>
  </link>

  <joint name="imu_joint" type="fixed">
    <axis xyz="1 0 0"/> <!-- 0 1 0 -->
    <origin xyz="0 0 0.25"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
  </joint>
  
  <!--xacro:include filename="$(find pluto)/urdf/pluto_plugins.xacro"/-->
</robot>
